services:
  aiohttp: &base_config
    build: ../aiohttp
    container_name: aiohttp-benchmark
    cpuset: "5"
    mem_limit: 1g
    mem_reservation: 1g
    memswap_limit: 1g
    networks: [benchmark-net]

  tornado:
    <<: *base_config
    build: ../tornado
    container_name: tornado-benchmark

  sanic:
    <<: *base_config
    build: ../sanic
    container_name: sanic-benchmark

  fastapi-standard:
    <<: *base_config
    build: ../fastapi-standard
    container_name: fastapi-standard-benchmark

  litestar-standard:
    <<: *base_config
    build: ../litestar-standard
    container_name: litestar-standard-benchmark

networks:
  benchmark-net:
    name: shared-benchmark-net
    driver: bridge
